class Dummy {
 static List<String> fruits = [
    'Apple',
    'Apricot',
    'Avocado',
    'Banana',
    'Blackberry',
    'Blueberry',
    'Boysenberry',
    'Cantaloupe',
    'Cherry',
    'Clementine',
    'Coconut',
    'Cranberry',
    'Date',
    'Dragonfruit',
    'Durian',
    'Elderberry',
    'Feijoa',
    'Fig',
    'Goji berry',
    'Gooseberry',
    'Grape',
    'Grapefruit',
    'Guava',
    'Honeydew',
    'Huckleberry',
    'Jackfruit',
    'Jambul',
    'Jujube',
    'Kiwifruit',
    'Kumquat',
    'Lemon',
    'Lime',
    'Longan',
    'Lychee',
    'Mango',
    'Mangosteen',
    'Marionberry',
    'Melon',
    'Mulberry',
    'Nance',
    'Nectarine',
    'Orange',
    'Papaya',
    'Passionfruit',
    'Peach',
    'Pear',
    'Persimmon',
    'Pineapple',
    'Pitaya',
    'Plantain',
    'Plum',
    'Pomegranate',
    'Pomelo',
    'Prune',
    'Quince',
    'Raspberry',
    'Redcurrant',
    'Salak',
    'Satsuma',
    'Starfruit',
    'Strawberry',
    'Surinam cherry',
    'Tamarillo',
    'Tamarind',
    'Tangerine',
    'Tomato',
    'Ugli fruit',
    'Watermelon',
    'Yuzu',
    'Ackee',
    'Atemoya',
    'Barbados cherry',
    'Bilberry',
    'Black sapote',
    'Breadfruit',
    'Buddhas hand',
    'Calamondin',
    'Canistel',
    'Capulin cherry',
    'Cherimoya',
    'Chico fruit',
    'Cloudberry',
    'Crowberry',
    'Cucamelon',
    'Currant',
    'Damson',
    'Dekopon',
    'Dewberry',
    'Gac',
    'Galia melon',
    'Greengage',
    'Imbe',
    'Jabuticaba',
    'Jostaberry',
    'Kiwano',
    'Langsat',
    'Mamey sapote',
    'Miracle fruit',
    'Monstera deliciosa',
    'Mulberry',
    'Naranjilla',
  ];
}
